language: ruby
sudo: false
cache: bundler
before_install: gem install bundler
script: bundle exec rspec
rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.0
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
